image: Visual Studio 2017
environment:
  MYSQL_PWD: Password12!
  nodejs_version: "LTS"
services:
  - mysql
before_build:
  - set PATH=%PATH%;C:\Program Files\MySql\MySQL Server 5.7\bin
  - mysql -e "create database nhk_test;" --user=root
build_script:
  - gradlew.bat build
before_test:
  - gradlew.bat ktlint
test_script:
  - gradlew.bat test jacocoTestReport
